### ISSUE TITLE
Distinguish training page and documentation page on the front page

### ISSUE THREAD

**Issue by avouacr** [InseeFrLab/onyxia-ui#9]
As discussed lately with @marchufschmitt and @garronej, the documentation of Onyxia is currently very hard to reach : one has to go through the Training section to get to it. 

I'd suggest putting two separate buttons in the headers : 
- Training
- Documentation

To avoid bloating the headers, the new button could replace the "Community Space" one : it's a nice looking page, but it's not very useful in itself. Maybe some nice elements from this page could be merged with the Datalab front page.

@fcomte

**Comment by garronej** [comment]
Hi @avouacr!

Ok for me. Let's remove the link to sspcloud.fr from the header.

We can't however easily merge the datalab and the community page because the Onyxia code should be agnostic from the INSEE and Its SSPCloud.

Also, not a big deal but I mention it, this repo is a library of ui component this is an issue for Onyxia-web.

I'll remove the link today.
  
Best regards

**Comment by garronej** [comment]
Hi @avouacr,
It's finally done. 
Tell me if there is anything to change. 
![image](https://user-images.githubusercontent.com/6702424/147382689-27c04dc3-18bd-48ca-bdf4-9db3043555b1.png)

**Comment by avouacr** [comment]
@garronej 

Perfect, looks much more user friendly to me, thank you
